<?php

namespace Vendor\CustomGridComponent\Model\ResourceModel\Customer\Grid;

use Magento\Customer\Model\ResourceModel\Customer;
use Magento\Framework\Data\Collection\Db\FetchStrategyInterface as FetchStrategy;
use Magento\Framework\Data\Collection\EntityFactoryInterface as EntityFactory;
use Magento\Framework\Event\ManagerInterface as EventManager;
use Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult;
use Psr\Log\LoggerInterface as Logger;

class Collection extends SearchResult
{
    public function __construct(
        EntityFactory $entityFactory,
        Logger $logger,
        FetchStrategy $fetchStrategy,
        EventManager $eventManager,
        string $mainTable = 'customer_entity',
        ?string $resourceModel = null,
        ?string $identifierName = null,
        ?string $connectionName = null
    ) {
        $resourceModel = Customer::class;
        parent::__construct(
            $entityFactory,
            $logger,
            $fetchStrategy,
            $eventManager,
            $mainTable,
            $resourceModel,
            $identifierName,
            $connectionName
        );
    }

    protected function _initSelect()
    {
        return parent::_initSelect(); // TODO: Change the autogenerated stub
    }

    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}
